# Generated by Django 4.2 on 2023-08-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_variation',
            new_name='product',
        ),
    ]
