# Generated by Django 4.2 on 2023-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_remove_address_user_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
