# Generated by Django 4.2.1 on 2023-07-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='post_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
