# Generated by Django 4.2 on 2023-07-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_remove_address_user_address_user'),
        ('orders', '0005_remove_order_address_line_2_remove_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='carts.address'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
