# Generated by Django 4.2 on 2023-07-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_remove_address_user_address_user'),
        ('orders', '0006_orderproduct_address_orderproduct_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.address'),
        ),
    ]
