# Generated by Django 4.2 on 2023-08-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
