# Generated by Django 4.2 on 2023-08-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_delete_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.FloatField(null=True),
        ),
    ]
