# Generated by Django 4.2 on 2023-08-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_total',
            field=models.FloatField(null=True),
        ),
    ]
