# Generated by Django 4.2 on 2023-08-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderproduct_product_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_total',
        ),
    ]
