# Generated by Django 4.2 on 2023-08-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_orderproduct_product_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Order Placed', 'Order Placed'), ('Out for Delivery', 'Out for Delivery'), ('Cancelled', 'Cancelled')], default='New', max_length=20),
        ),
    ]
