# Generated by Django 4.2 on 2023-09-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Order Placed', 'Order Placed'), ('Out for Delivery', 'Out for Delivery'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(default='Order Placed', max_length=255),
        ),
    ]
